# Log Codes
WHI_CAF_LIB_CONFREADER_LOAD_CONFIG = ('CAFLIBCONFREADERLOG001', 'Loading config file {}')
WHI_CAF_LIB_CONFREADER_LOAD_SECRETS = ('CAFLIBCONFREADERLOG002', 'Loading secrets from {}')
WHI_CAF_LIB_CONFREADER_LOAD_SECRETS_FILE = ('CAFLIBCONFREADERLOG003', 'Reading secrets file {}')

# Error Codes
WHI_CAF_LIB_CONFREADER_FILE_NOT_FOUND = ('CAFLIBCONFREADERERROR001', 'Config file not found at {}')
WHI_CAF_LIB_CONFREADER_SECRETS_DIR_NOT_FOUND = ('CAFLIBCONFREADERERROR002', 'Secrets directory not found at {}')
WHI_CAF_LIB_CONFREADER_SECRET_NOT_FOUND = ('CAFLIBCONFREADERERROR003', 'Secret {} not found')
WHI_CAF_LIB_CONFREADER_KEYS_MISSING = (
    'CAFLIBCONFREADERERROR004', 'Invalid configurations. Key {} not found under the section {}')
WHI_CAF_LIB_CONFREADER_SECTION_NOT_FOUND = ('CAFLIBCONFREADERERROR004', 'Section {} not found in the config file')
